### ISSUE TITLE
Monitor Topic Hierarchy level 4: NULL

### ISSUE THREAD

**Issue by chenxiaoxia2019** [wmo-im/wis2-monitoring-alerting#4]
![image](https://github.com/user-attachments/assets/26b49ed2-8ee0-43e2-95ad-3a5ed3c2e326)
It is observed that monitor/a/wis2//bb-barbadosmetservices missing level 4 when subscribing to GB (France). Any comment?

**Comment by tomkralidis** [comment]
@chenxiaoxia2019 thanks for the feedback.  I am closing this issue given it is not an issue with the specification, but an implementation of same (cc @golfvert).
